import Footer from "@/components/common/Footer";
import ScrollManager from "@/components/common/ScrollManager";
import SmoothScrollProvider from "@/components/common/SmoothScrollProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FloatingDockNav from "@/components/common/FloatingDockNav";

// Local fonts from public/fonts
const outfit = localFont({
  src: "../../public/fonts/Outfit-VariableFont_wght.ttf",
  variable: "--font-outfit",
  weight: "100 900",
  display: "swap",
});

const playfair = localFont({
  src: "../../public/fonts/PlayfairDisplay-VariableFont_wght.ttf",
  variable: "--font-playfair",
  weight: "100 900",
  display: "swap",
});

const spaceGrotesk = localFont({
  src: "../../public/fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-space-grotesk",
  weight: "300 700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${playfair.variable} ${spaceGrotesk.variable} antialiased`}>
        <SmoothScrollProvider>
          <ScrollManager />
          {children}
          <FloatingDockNav />
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
